#!/usr/bin/env node
'use strict';
const parseInput = require('./lib/parseInput.js');
const findPath = require('./lib/findPath.js');
const ask = require('./lib/ask-for-input.js');

function pizzabot(input) {
  let parsed = parseInput(input);
  let path = findPath(parsed);
  process.stdout.write(path + '\n');
  process.exit(0);
}

/*
 * If data was passed as an argument via the command line we can
 * handle it directly
 */
let input = process.argv[2];
if (input) {
  pizzabot(input);
}

/*
 * If user only typed `./pizzabot` without passing arguments
 * then we can prompt the user and get data via stdin
 */
ask("Please enter pizzabot's delivery data:")
  .then(function(line){
    pizzabot(line);
  })
  .catch(function(err){
    console.error(err);
  });